console.log("Menor que:")
console.log(4<3)
console.log("Mayor que:")
console.log(4>3)
console.log("Menor o igual que:")
console.log(4<=3)
console.log("Mayor o igual que:")
console.log(4>=3)
console.log("Igualdad:")
console.log(4==3)
console.log("No igualdad:")
console.log(4!=3)
