console.log("Suma:")
console.log(4+3)
console.log("Resta:")
console.log(4-3)
console.log("Multiplicación:")
console.log(4*3)
console.log("División:")
console.log(4/3)
console.log("Resto entero de la división:")
console.log(4%3)